version: 2.1

jobs:
  node-test:
    working_directory: ~/rntemplate/template
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout: # load source code into circleci
          path: ~/rntemplate
      - restore_cache: # pre-defined step to restore cache, if available
          key: node-v1-{{ checksum "package.json" }}--{{ arch }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}--{{ arch }}
          paths:
            - node_modules
      - run:
          name: Run App.tsx tests
          command: npm run test:app
      - run:
          name: Run component tests
          command: npm run test:components
      - run:
          name: Run containers tests
          command: npm run test:containers
      - run:
          name: Run screens tests
          command: npm run test:screens
      - run:
          name: Lint
          command: npm run lint
      - persist_to_workspace:
          root: ~/rntemplate/template
          paths:
            - node_modules

  android-build: 
    working_directory: ~/rntemplate/template/android
    docker:
       - image: cimg/android:2023.12-node
    steps:
      - checkout:
          path: ~/rntemplate
      - attach_workspace:
          at: ~/rntemplate
      - restore_cache: # pre-defined step to restore cache, if available
          key: node-v1-{{ checksum "package.json" }}--{{ arch }}
      - run: cd .. && npm i && cd android
      # Install Ninja, CMake (Begin)
      - run:
          name: Install Ninja
          command: |
            sudo apt-get update && sudo apt-get install -y ninja-build
      - run:
          name: Install CMake
          command: |
            wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-Linux-x86_64.tar.gz
            tar -xzvf cmake-3.22.1-Linux-x86_64.tar.gz -C $HOME
            export PATH=$HOME/ninja:$HOME/cmake-3.22.1-Linux-x86_64/bin:$PATH
      - run:
          name: Set CMake and Ninja Paths
          command: |
            export PATH=$HOME/ninja:$HOME/cmake-3.22.1-Linux-x86_64/bin:$PATH
      # Install Ninja, CMake (End)
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - save_cache:
          paths:
            - .gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: 
          name: Update .gradlew permission
          command: chmod +x ./gradlew
      - run:
          name: Assemble Debug APK
          command: ./gradlew assembleDebug
  

workflows:
  test-lint:
    jobs:
      - node-test
      - android-build:
          requires:
            - node-test
          filters:
            branches:
              only: main
